### ISSUE TITLE
declarative_base moved between SQL Alchemy 1.3.x and 1.4.x

### ISSUE THREAD

**Issue by HaakonME** [agronholm/sqlacodegen#132]
sqlacodegen supports SQL Alchemy 1.3.x, but if you are on 1.4.x and want to try sqlacodegen, note declarative_base has been moved between 1.3.x and 1.4.x, so sqlacodegen's output model must be changed from 

```
from sqlalchemy.ext.declarative import declarative_base

```

to

```
from sqlalchemy.orm import declarative_base
```

Please see https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.declarative_base

**Comment by mzpqnxow** [comment]
This is also [documented](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html) as "SQL Alchemy 2.0" behavior so I believe it will move from a deprecation warning to a hard failure once 2.x is released. I'm assuming `sqlalchemy.ext.declarative` will disappear and will then become an `ImportError` rather than a warning

If anyone wants to help identify any other possible warnings drawn out by code emitted by `sqlacodegen` you can use the following at the top of your entry-point, or put it at the top-most `__init__.py` in the case of a package:

```
import os
import sys
import warnings

os.environ['SQLALCHEMY_WARN_20'] = 'yes'
if not sys.warnoptions:
    warnings.simplefilter("default")
```

The warning for the `declarative_base` import  issue looks like this:

```
MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 1.4) (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  Base = declarative_base()
```

@agronholm I figure there are at least three straightforward ways to solve this:

1. You could have `sqlacodegen` assume that the version of `SQLAlchemy` that the users' project runs under will be the same as that which `sqlacodegen` is running under and check at runtime version of `SQLAlchemy` in `sqlacodegen`, emitting the correct import depending on the version of `SQLAlchemy`. This is probably not ideal since it's quite possible for the versions to differ, probably
2. Disregard the current version of `SQLAlchemy` that `sqlacodegen` is using and emit portable imports, with a try/except wrapped around the pre-1.4 import that falls back to the >= 1.4 import. This seems like the best option, it's simple and the least invasive, I think
3. Force the user to specify what they want to be emitted via a command-line option and leave the default behavior the same. This is fine but users may not be too aware of this issue. It would be nice to save them the trouble and provide the portability by default

## Option 1: Check SQLAlchemy version at `sqlacodegen` run-time

Add something like the following:

```
# Forgive this hacky version logic, it's ugly but works and has no third-party dependencies
import sqlalchemy
...
SQLA_MINOR, SQLA_MAJOR = (int(v[0]) for v in sqlalchemy.__version__.split('.')[:2])
USE_SQLALCHEMY_20 = (SQLA_MAJOR * 100 + SQLA_MINOR) >= 104:
DECLARATIVE_BASE_IMPORT = 'sqlalchemy.ext.declarative' if SQLALCHEMY20 else 'sqlalchemy.orm'
...
```

Then replace the relevant `add_literal_import` call

https://github.com/agronholm/sqlacodegen/blob/2531d8beec6dae0177c175967c124476e338ed17/src/sqlacodegen/codegen.py#L472

This would become:

```
self.collector.add_literal_import(DECLARATIVE_BASE_IMPORT, 'declarative_base')
```

## Option 2: Emit portable imports using try/except

Or, as portable code so it will run on either version, emit the following. I don't have a snippet to emit try/except inside `codegen.py`, but the emitted code would be:

```
try: 
    from sqlalchemy.ext.declarative import declarative_base
except ImportError:
    from sqlalchemy.orm import declarative_base
```

## Option 3: Force the user to explicitly specify what they want

Add something like `--legacyt`, `--new` and/or `--compat`


If you have a preference (or maybe something better) I'm happy to send a PR for it based on your feedback. The version check is ugly, I know, but I'm not sure you want to introduce any dependencies for such a simple task as comparing a major and minor version

**Comment by agronholm** [comment]
I have already solved this locally. I have changes that not only fix the declarative import but optionally also emit dataclass based ORM classes. I need to clean up this code and write tests before I can commit it to Github.

**Comment by mzpqnxow** [comment]
> I have already solved this locally. I have changes that not only fix the declarative import but optionally also emit dataclass based ORM classes. I need to clean up this code and write tests before I can commit it to Github.

Well shux, I guess i should close #143 then hah. I'm curious to see how you did it, I'm not too happy with how my changes came out

**Comment by mzpqnxow** [comment]
Also FYI- I won't open up a separate issue for unless you would like me to, but I am seeing one additional warning regarding SQLAlchemy changes:

```
RemovedIn20Warning: The MetaData.bind argument is deprecated and will be removed in SQLAlchemy 2.0. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  metadata = MetaData(engine)
```

Maybe I'm a dimwit but it isn't immediately clear to me how to "fix" this one

**Comment by agronholm** [comment]
> Maybe I'm a dimwit but it isn't immediately clear to me how to "fix" this one

By not passing any bind parameter to `MetaData()`. It's not really needed. I've committed this change in b468490d.

**Comment by agronholm** [comment]
As for this particular issue, I've fixed it in 2d4b7ab7.

**Comment by agronholm** [comment]
Seems I was too hasty about not needing `metadata.bind`. I was only thinking of the actual reflection phase. I'll ask around and get back to you on this.

**Comment by agronholm** [comment]
Ok, so I just need to refactor the code to carry the bind value everywhere it's needed. I'll push more code soon-ish.
