### ISSUE TITLE
"ForeignKey" not imported

### ISSUE THREAD

**Issue by amacfie** [agronholm/sqlacodegen#182]
On version 3.0.0b3 I got an output that had `ForeignKey` fields but there was no `from sqlalchemy import ForeignKey`.

**Comment by Distortedlogic** [comment]
same issue for me

**Comment by agronholm** [comment]
The test suite does have tests that ensure `ForeignKey` is imported. Could either one of you post a schema (and tell me what RDBMS this was on) that triggers this problem?

**Comment by leonarduschen** [comment]
The actual issue is not that we are missing `Foreignkey` import, but rather we wrongly define ForeignKey constraint as parameter of the column even when we already have `ForeignKeyConstraint` in `__table_args__`.

The following line is missing an extra condition `uses_default_name(c.constraint)` :
https://github.com/agronholm/sqlacodegen/blob/ab0353f9499d340e98ffeac141982d2e535c0536/src/sqlacodegen/generators.py#L350

This is what I'm addressing in #189 

---

The issue can be reproduced using the schema in the test that I added in the PR:
```python
def test_named_foreign_key_constraints(self, generator: CodeGenerator) -> None:
    Table(
        'simple_items', generator.metadata,
        Column('id', INTEGER, primary_key=True),
        Column('container_id', INTEGER),
        ForeignKeyConstraint(['container_id'], ['simple_containers.id'], name='foreignkeytest')
    )
    Table(
        'simple_containers', generator.metadata,
        Column('id', INTEGER, primary_key=True)
    )
```

Code generated:
```python
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class SimpleContainers(Base):
    __tablename__ = 'simple_containers'

    id = Column(Integer, primary_key=True)

    simple_items = relationship('SimpleItems', back_populates='container')


class SimpleItems(Base):
    __tablename__ = 'simple_items'
    __table_args__ = (
        ForeignKeyConstraint(['container_id'], ['simple_containers.id'], name='foreignkeytest'),
    )

    id = Column(Integer, primary_key=True)
    container_id = Column(ForeignKey('simple_containers.id')) # SHOULD HAVE BEEN container_id = Column(Integer)

    container = relationship('SimpleContainers', back_populates='simple_items')
```
