### ISSUE TITLE
--generator sqlmodels unavailable

### ISSUE THREAD

**Issue by gitkeerthi** [agronholm/sqlacodegen#219]
```
$ sqlacodegen --version                                             
3.0.0rc1
```
```
$ sqlacodegen --generator sqlmodels postgresql+psycopg2://*********@localhost/*****
usage: sqlacodegen [-h] [--option [OPTION ...]] [--version] [--schemas SCHEMAS] [--generator {dataclasses,declarative,tables}]
                   [--tables TABLES] [--noviews] [--outfile OUTFILE]
                   [url]
sqlacodegen: error: argument --generator: invalid choice: 'sqlmodels' (choose from 'dataclasses', 'declarative', 'tables')
```

But your README says otherwise.

**Comment by agronholm** [comment]
If you took the time to read the [changelog](https://github.com/agronholm/sqlacodegen/blob/master/CHANGES.rst), you would notice that the feature has not yet been released.

**Comment by gitkeerthi** [comment]
Rather you should have taken time and not publish a README with something that was not related lmao

**Comment by agronholm** [comment]
I didn't publish it in a release, did I? Do you have any clue about how open source development works?

**Comment by marc-odp** [comment]
Not well obviously.

**Comment by marc-odp** [comment]
I mean... Having the readme mentioning a feature that was not released doesn't make any sense and you should probably edit the readme asap.

**Comment by agronholm** [comment]
The [README](https://pypi.org/project/sqlacodegen/3.0.0rc1/) on PyPI does not mention SQLModel support. If you're reading the README on GitHub where the latest code lives, then feel free to install that code straight from VCS and use that feature. But it's unreasonable to expect README (and changelog, I assume) changes to be deferred in VCS too until a release happens instead of happening directly in the pull requests.
