### ISSUE TITLE
sqlmodels

### ISSUE THREAD

**Issue by kailashlimba1997** [agronholm/sqlacodegen#238]
NOT able to use sqlmodels generator. 
I'm getting below mentioned error. 

sqlacodegen: error: argument --generator: invalid choice: 'sqlmodels' (choose from 'dataclasses', 'declarative', 'tables')

I'm using latest sqlacodegen version i.e. 3.0.0rc1
Can you guide me how can I use sqlmodels generator.

**Comment by agronholm** [comment]
This feature is only in master, and has not been released yet. I don't remember if it currently works at all, but you can try your luck by installing from master directly: `pip install "sqlacodegen @ git+https://github.com/agronholm/sqlacodegen.git"`

**Comment by krezer** [comment]
> This feature is only in master, and has not been released yet. I don't remember if it currently works at all, but you can try your luck by installing from master directly: `pip install "sqlacodegen @ git+https://github.com/agronholm/sqlacodegen.git"`

Hi @agronholm, thank you for this great tool! It works for me with version 3.0.0rc1.post22. I had only to pin sqlalchemy to v 1.4.43 because with the newer version 2.0.0 your package got
`AttributeError: module 'sqlalchemy' has no attribute '__all__`
(s. https://github.com/pallets-eco/flask-sqlalchemy/issues/1122)

**Comment by agronholm** [comment]
Yup, sqlmodel itself does not support SQLAlchemy 2.0 at all yet.
