### ISSUE TITLE
Support ManyToMany realtionship tables (+2 col·lumns).

### ISSUE THREAD

**Issue by EndermanAPM** [agronholm/sqlacodegen#90]
I'm working with a Schema that is used as the backend of an already existing Prestashop.
As it's well know, PS doesn't shine regarding the compliance with best practices. 

I encountered that the relation table "ps_category_product" does not have two columns (id_category and id_product) but an additional column called "position". I believe that this additional column is messing up the generation and I was wondering if a workarround is possible without altering the schema. (I don't currently need the column position and it could be ignored)

Here is a [pastebin](https://pastebin.com/8W7CigfC) with the output.

Regards.

**Comment by agronholm** [comment]
Using such tables as association tables is bad practice in SQLAlchemy because you would not be able to access the additional columns. That is why support is not, and will not be provided as automatically using those as m2m tables in sqlacodegen.

Remember that the purpose of sqlacodegen is to save you the work of typing a lot of code manually. It was never expected to generate perfect results for every use case, but "close enough" so you can get your schema to work with minimal editing.
